// Catálogo de funciones por cargo (Consolidado de Funciones y Cargos).
// Se usa para autocompletar las ACTIVIDADES IMPORTANTES DENTRO DE LA JORNADA
// LABORAL (Sección G del formulario de Evaluación Médica Ocupacional): al
// elegir el cargo del trabajador se proponen sus primeras funciones.
// Generado desde el CSV institucional; editable a mano si cambian los perfiles.

export interface PerfilCargo {
  departamento: string;
  cargo: string;
  funciones: string[];
}

/** Nº de funciones que se autocompletan por defecto (las más representativas). */
export const FUNCIONES_AUTOCOMPLETAR = 6;
/** Máximo de actividades que admite la matriz del formato oficial. */
export const MAX_ACTIVIDADES = 7;

export const PERFILES_CARGO: PerfilCargo[] = [
  { departamento: "TALENTO HUMANO", cargo: "ANALISTA DE REMUNERACIONES", funciones: [
    "Elaborar los roles de compensaciones económicas y beneficios sociales",
    "Elaborar las liquidaciones de haberes y actas de finiquito del personal",
    "Elaborar informes periódicos de gestión, así como preparar documentación requerida por su jefe inmediato",
    "Elaborar, revisar y procesar la información referente a obligaciones patronales con el IESS",
    "Realizar el cuadre de planillas del IESS con lo valores calculados y generados en los roles de pago",
    "Llevar el control de vacaciones y asistencia del personal",
    "Ingresar, procesar y verificar la información referente a: movimientos de personal, descuentos, ascensos, nuevos contratos, retenciones, horas extras, entre otros",
    "Mantener actualizado y en custodia los archivos de las carpetas personales de los servidores y obreros de la Compañía",
    "Mantener actualizado el sistema informático, con información referente al personal de la Compañía",
    "Analizar el nivel de endeudamiento del personal de la Compañía",
    "Elaborar, proponer y aplicar los indicadores de gestión para el área",
    "Ingresar y actualizar información en el sistema automatizado del Ministerio del Trabajo",
    "Ingresar y registrar información del personal en el sistema del Instituto Ecuatoriano de Seguridad Social",
    "Verificar información y tramitar los descuentos por retenciones judiciales (SUPA)",
    "Dar información sobre compensaciones, beneficios y descuentos al personal",
    "Custodiar los archivos institucionales referentes a los procesos relacionados con su gestión; así como mantener ordenado y con los documentos de respaldo",
    "Elaborar comunicaciones como: memorandos, oficios, entre otros",
    "Elaborar informes para la adquisición de bienes, obras y/o servicios relacionados con su gestión",
    "Administrar contratos de bienes y/o servicios",
    "Receptar, revisar e ingresar las proyecciones de gastos personales",
    "Cumplir con las normas de seguridad y salud en el trabajo",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía"
  ] },
  { departamento: "TALENTO HUMANO", cargo: "JEFE/A DE TALENTO HUMANO", funciones: [
    "Planificar un adecuado y permanente desarrollo del talento humano, a fin de poder cumplir en forma eficiente con la prestación de los servicios que brinda la Compañía",
    "Cumplir con las leyes, normas, regulaciones y disposiciones impartidas por los organismos de control, para el adecuado manejo del talento humano de la Compañía",
    "Gestionar programas para el aseguramiento del bienestar integral (salud e intervención social) del talento humano de la Compañía",
    "Gestionar el cumplimiento y aplicación de los subsistemas de gestión del talento humano de la Compañía",
    "Aplicar medidas correctivas recomendadas por entes reguladores o de auditoría interna y/o externa",
    "Elaborar y poner a consideración de la Gerencia: manuales, políticas y procedimientos para la efectiva gestión del departamento y sus unidades a cargo",
    "Reportar la gestión cumplida del departamento, así como preparar informes requeridos por la Gerencia",
    "Asesorar a las diferentes áreas, departamentos y personal de la Compañía, en lo relativo a los subsistemas de gestión del talento humano",
    "Realizar la actualización de los perfiles por competencias, según requerimientos de la Compañía",
    "Proponer programas para el mejoramiento del clima laboral y la cultura organizacional del talento humano",
    "Coordinar la comunicación Interna de la Compañía, en temas relacionados con el talento humano",
    "Realizar la planificación del talento humano y elaborar el presupuesto de gastos de personal; y el presupuesto del departamento, el mismo que lo pone a consideración de la Gerencia",
    "Proponer el plan de capacitación y formación anual del talento humano, en función de las necesidades de las áreas y departamentos, de acuerdo con los requisitos de competencias exigidos en los perfiles",
    "Proponer procesos de: valoración de cargos, estructuración y remuneración del talento humano de la Compañía",
    "Elaborar informes para la adquisición de bienes, obras y/o servicios relacionados con su gestión"
  ] },
  { departamento: "TALENTO HUMANO", cargo: "MENSAJERO/A", funciones: [
    "Entregar y retirar la correspondencia, documentos y encomiendas dentro y fuera de la Compañia",
    "Realizar depósitos en bancos",
    "Efectuar trámites en bancos y otras instituciones",
    "Conducir el vehículo asignado por la empresa para transportar, personal, materiales etc., para el desarrollo de sus funciones",
    "Efectuar la distribución de la correspondencia, servicio de mensajería interna y externa, paquetería y demás documentos",
    "Realizar el registro de documentos entregados (Hoja de Ruta)",
    "Hacer firmar las hojas de ruta por las gestiones realizadas",
    "Cumplir con las politicas y procedimientos definidos por la Compañía",
    "Fotocopiar documentación",
    "Velar por el buen estado del vehículo asignado, mantener al día la limpieza y mantenimientos del vehículo",
    "Custodiar la documentación bajo su cargo",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía",
    "Cumplir las normas de seguridad y salud en el trabajo"
  ] },
  { departamento: "COMERCIAL", cargo: "JEFE/A COMERCIAL", funciones: [
    "Proponer a la Compañía tarifas para la comercializacion de GLP (Gas Licuado de Petróleo), industrial, agroindustrial y doméstico",
    "Dirigir las actividades concernientes a la comercialización de GLP, de acuerdo con las normas y procedimientos establecidos por la Compañía",
    "Cumplir con las leyes, normas, regulaciones y disposiciones impartidas por los organismos de control, para el adecuado manejo comercial de la Compañía",
    "Elaborar y poner a consideración de la Gerencia: manuales, políticas y procedimientos para la efectiva gestión del departamento y sus unidades a cargo",
    "Elaborar y poner a consideración de la Gerencia: estudios de mercado, a fin de proponer un plan de negocios, que permitan identificar estrategias y proyectos de expansión para la Compañía, en coordinación con el departamento de Planificación",
    "Aplicar medidas correctivas recomendadas por entes reguladores o de auditoria interna y/o externa",
    "Evaluar la gestión y proponer alternativas que permitan el mejoramiento de la satisfacción del cliente o la mejora institucional",
    "Reportar la gestión cumplida del departamento, así como preparar documentación requerida por la Gerencia",
    "Brindar asesoría e información a las diferentes áreas, departamentos y personal de la Compañía, en lo relativo a la gestión comercial",
    "Realizar visitas e inspecciones a los clientes, con el propósito de establecer mejoras de los servicios que brinda la Compañía",
    "Presentar la proyección de ingresos a la Gerencia",
    "Atender y ofrecer soluciones a los clientes",
    "Elaborar informes para la adquisición de bienes, obras y/o servicios relacionados con su gestión",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser asi designado",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir con las normas de seguridad y salud en el trabajo",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía"
  ] },
  { departamento: "COMERCIAL", cargo: "ANALISTA DE SERVICIO AL CLIENTE", funciones: [
    "Coordinar y gestionar la recepción, envío de GLP en cilindros de forma oportuna a los distribuidores del Austro, incluidos los operativos sociales designados por el Estado para la comercialización de GLP",
    "Apoyar a la jefatura comercial en las actividades relacionadas con la atención a los clientes",
    "Elaborar comunicaciones internas y externas, relacionadas con los procesos y servicios que brinda el departamento comercial",
    "Captar nuevos y potenciales clientes ofertando los productos de la compañía",
    "Mantener actualizado y ordenado los archivos de documentos de la unidad de servicio al cliente",
    "Realizar visitas periódicas a los clientes (distribuidores, etc.) con la finalidad de posicionar la marca y dar a conocer los productos de la compañía",
    "Canalizar los reclamos presentados por los clientes y distribuidores, para direccionar a las diferentes áreas y brindar una solución a sus requerimientos",
    "Ejecutar las acciones correspondientes a los resultados de la evaluación de la encuesta de satisfacción al cliente realizada por la compañía",
    "Tramitar los documentos necesarios, de acuerdo con el procedimiento establecido para: otorgamiento de cilindros en comodato a los distribuidores de GLP doméstico e industrial, registros de vinculación de nuevos distribuidores, autorización y registro de permisos para la distribución de GLP",
    "Elaborar informes de la gestión, de acuerdo a las solicitudes realizadas por su jefe inmediato",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser asi designado",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir con las normas de seguridad y salud en el trabajo",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía"
  ] },
  { departamento: "COMERCIAL", cargo: "TÉCNICO/A DE INSTALACIONES CENTRALIZADAS", funciones: [
    "Realizar inspecciones a las instalaciones centralizadas de los clientes de la compañía, para verificar su correcto funcionamiento",
    "Analizar los resultados de las inspecciones a las instalaciones centralizadas y tanques estacionarios, con la finalidad de generar un plan de acción para la mejora del servicio",
    "Elaborar las rutas y monitorear la ubicación de los graneleros, a fin de garantizar un adecuado y oportuno servicio",
    "Realizar el cuadre de bodegas de GLP, en coordinación con los inspectores de granelero",
    "Coordinar, controlar y supervisar el abastecimiento de GLP para las instalaciones centralizadas, con el personal de granel",
    "Llevar el control de los kilogramos de GLP entregado a los clientes",
    "Realizar el seguimiento respectivo del tipo de GLP que se entrega a los clientes de instalaciones centralizadas",
    "Elaborar los reportes mensuales de ventas de GLP",
    "Apoyar a su jefe inmediato en la elaboración de procesos, políticas y procedimientos correspondientes a su gestión",
    "Gestionar y coordinar las novedades presentadas en las instalaciones centralizadas y tanques estacionarios, al momento del abastecimiento",
    "Revisar y aplicar la normativa legal vigente, emitida por los organismos de control, como la ARCERNNR entre otros",
    "Preparar informes relativos al cumplimiento de la gestión del área",
    "Custodiar, mantener ordenado y actualizado el archivo de documentos de la gestión realizada para los clientes de instalaciones centralizadas de manera física y digital",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser asi designado",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir con las normas de seguridad y salud en el trabajo",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía"
  ] },
  { departamento: "COMERCIAL", cargo: "ASISTENTE DE INSTALACIONES CENTRALIZADAS", funciones: [
    "Realizar visitas a los actuales y posibles clientes de GLP a granel, con el objetivo de incrementar las ventas",
    "Recopilar la documentación de nuevos clientes y remitirlos al departamento Legal para la elaboración del contrato de servicios, para abastecimiento de GLP, y comodato de tanques estacionarios",
    "Elaborar los comunicados dirigidos al organismo de control, para la aprobación de permisos de funcionamiento de las instalaciones centralizadas",
    "Custodiar, mantener ordenado y actualizado el archivo de documentos de la gestión realizada por instalaciones centralizadas",
    "Receptar las novedades presentadas en las instalaciones centralizadas al momento del abastecimiento a las estaciones centralizadas o tanques estacionarios",
    "Ingresar información de nuevos clientes en el sistema ERP",
    "Realizar el inventario de GLP de los tanques estacionarios y remitir la información para la facturación y cobro a los clientes",
    "Registrar los datos de la entrega de GLP realizada a los clientes de manera diaria, a fin de que se proceda con la respectiva facturación",
    "Administrar préstamos e inventarios de tanques estacionarios en la planta Cuenca",
    "Realizar inspecciones periódicas, para el adecuado funcionamiento de las instalaciones centralizadas y tanques estacionarios de los clientes; así como realizar el inventario mensual de GLP en los tanques estacionarios de la compañía",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser asi asignado",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir con las normas de seguridad y salud en el trabajo",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía"
  ] },
  { departamento: "COMERCIAL", cargo: "INSPECTOR DE GRANELERO", funciones: [
    "Cumplir el procedimiento de carga y descarga de GLP en el camión granelero",
    "Inspeccionar el estado de las instalaciones centralizadas con la finalidad de detectar fugas de GLP previo a la descarga en las estaciones centralizadas",
    "Descargar GLP en los tanques estacionarios ubicados en las instalaciones de los clientes, cumpliendo protocolos de seguridad y de acuerdo con la ruta establecida",
    "Colaborar en la planificación de las rutas diarias, de acuerdo con los requerimientos de los clientes",
    "Realizar inspecciones a las instalaciones centralizadas de los clientes, con la finalidad de brindar asesoramiento respecto a las medidas correctivas o preventivas que se deben adoptar",
    "Coordinar el abastecimiento del GLP con el operador de granelero",
    "Entregar los formatos de venta diaria con los despachos realizados al técnico de instalaciones centralizadas",
    "Revisar constantemente el camión granelero para constatar el estado del motor, neumáticos, sistema eléctrico, sistema hidráulico, limpieza en general, etc., para informar si se requiere un mantenimiento preventivo o correctivo del mismo",
    "Registrar y reportar: destinos, tiempos, kilometraje, consumo de combustible, daños mecánicos y daños materiales",
    "Apoyar en la logística para los mantenimientos preventivos y correctivos en el taller mecánico designado por servicios generales",
    "Apoyar con el intercambio de cilindros desde y hacia los centros de distribución asignados por su jefe inmediato",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo",
    "Velar por el buen uso de los recursos equipos e instalaciones asignados por la compañía que están bajo su responsabilidad"
  ] },
  { departamento: "COMERCIAL", cargo: "OPERADOR DE GRANELERO", funciones: [
    "Realizar el control de niveles de cantidad de GLP en el granelero",
    "Conectar las mangueras de abastecimiento en la isla de descarga",
    "Apoyar en la distribución de GLP y conexión de mangueras surtidoras a la línea de carga de los diferentes locales de clientes, mediante protocolos de seguridad",
    "Realizar el control del llenado del tanque de la estación centralizada",
    "Verificar fugas de GLP al momento de la descarga en las estaciones centralizadas",
    "Colaborar en la planificación de las rutas diarias en conjunto con el inspector de granel, de acuerdo con los requerimientos presentados por los clientes",
    "Informar al responsable de los diferentes locales de abastecimiento sobre: medidas de seguridad y procedimientos para el despacho",
    "Apoyar en la inspección de las instalaciones centralizadas de los clientes, con la finalidad de asesorar al cliente respecto a las medidas correctivas o preventivas que se deben adoptar",
    "Revisar que las instalaciones centralizadas cumplan con las normas básicas de seguridad, requisito necesario para la carga de GLP",
    "Registrar los datos de despacho en el lugar de la estación centralizada, utilizando el formulario de venta granelero",
    "Informar al operador de granelero por radio el inicio y la terminación del bombeo de GLP",
    "Apoyar en el mantenimiento de granelero en su parte funcional",
    "Apoyar en la logística de despacho de GLP a las instalaciones centralizadas, conduciendo el camión granelero cuando sea requerido",
    "Apoyar con el intercambio de cilindros desde y hacia los centros de distribución asignados por su jefe inmediato",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo",
    "Velar por el buen uso de los recursos equipos e instalaciones asignados por la compañía que están bajo su responsabilidad"
  ] },
  { departamento: "JEFATURA ADMINISTRATIVA", cargo: "ANALISTA DE CONTRATACIÓN PÚBLICA", funciones: [
    "Elaborar y publicar el plan anual de contrataciones, en coordinación con las jefaturas departamentales",
    "Revisar las especificaciones técnicas y/o términos de referencia para la contratación de bienes y/o servicios",
    "Elaborar los pliegos para preparar los procesos de contratación pública; los mismos que deben ser revisados por la unidad requirente y asesoría legal",
    "Asesorar a las diferentes áreas de la compañía, en temas relacionados con los procesos de contratación pública, definidos en el Sistema Nacional de Contratación Pública",
    "Dar seguimiento a todos los procesos de contratación pública publicados en el portal, según su cronograma, vigilando permanentemente el cumplimiento de las etapas del proceso de contratación, en las etapas: preparatoria, precontractual y contractual",
    "Publicar la información de cada proceso de contratación en el portal de compras públicas",
    "Custodiar y dar seguimiento de los accesos de seguridad al portal de compras públicas",
    "Elaborar las certificaciones de catálogo electrónico junto con las resoluciones de procesos",
    "Presentar informes inherentes a la gestión realizada",
    "Elaborar órdenes de compra de los contratos de los procesos de Contratación Pública",
    "Elaborar órdenes de compra de la adquisición del GLP",
    "Ingresar a proveedores nuevos en el sistema ERP, valoración de requerimiento de compras",
    "Solicitar el pago de servicios básicos",
    "Solicitar informes de pertinencia para los procesos de contratación pública cuando asi sea requerido",
    "Elaborar las ofertas de contratación para el sector público cuando sea requerido",
    "Realizar los trámites necesarios para calificar a la compañía como proveedor del Estado; así como mantener la calificación vigente en el portal de compras públicas",
    "Custodiar y gestionar los expedientes de los procesos de Contratación Pública",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir con las normas de seguridad y salud en el trabajo"
  ] },
  { departamento: "JEFATURA ADMINISTRATIVA", cargo: "ANALISTA DE SERVICIOS GENERALES", funciones: [
    "Controlar el transporte de la Compañía, asignando responsables y vehículos, con el fin de ofrecer un servicio de manera planificada eficiente y eficaz",
    "Planificar, coordinar y controlar el mantenimiento preventivo y correctivo de la flota vehicular de la Compañía, con el fin de dar continuidad y disponibilidad de este servicio",
    "Efectuar el control de los servicios contratados de seguridad privada",
    "Realizar la matriculación vehicular, de la flota de vehículos de la Compañía",
    "Coordinar el apoyo de los vehículos siniestrados en la Compañía; así como notificar a su jefe inmediato y a la empresa de Seguros sobre los siniestros ocurridos",
    "Realizar los trámite para la renovación de: permisos de funcionamiento, bomberos, ARCERNNR, permisos municipales, permisos para autotanques, graneleros, entre otros",
    "Coordinar actividades del personal de servicios generales en el edificio administrativo y planta",
    "Revisar, controlar y gestionar el consumo de combustible de la flota vehicular de la Compañía",
    "Realizar informes técnicos y de gestión, así como preparar documentación de acuerdo a las necesidades de la compañía",
    "Programar las adecuaciones de oficinas, en coordinación con los responsables de cada departamento",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser así designado",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía"
  ] },
  { departamento: "JEFATURA ADMINISTRATIVA", cargo: "ANALISTA DE INVENTARIOS Y ACTIVOS FIJOS", funciones: [
    "Realizar el cuadre de inventarios de GLP, de acuerdo con las existencias y las cuentas contables, en el sistema automatizado; así como presenta informes a su jefe inmediato",
    "Realizar la constatación física de GLP en todos los tanques estacionarios de la Compañía",
    "Realizar el cuadre de inventarios de cilindros, según los datos constantes en el sistema automatizado; así como presentar informe a su jefe inmediato",
    "Elaborar, suscribir, controlar y dar seguimiento de las actas de entrega recepción por el ingreso, transferencia de bienes a nivel interno, egresos y bajas de acuerdo a las normas legales vigentes",
    "Realizar la constatación física de cilindros de GLP y cilindros de las plantas de Cuenca, Ventanas y Planta Chorrillos",
    "Evaluar las condiciones de existencia y estado de utilización de los bienes con los que cuenta la Compañía",
    "Realizar la constatación física de suministros de oficina, repuestos y accesorios, constantes en la Bodega de la Compañía",
    "Realizar el levantamiento físico de bienes de toda la Compañía con el fin de mantener información actualizada",
    "Organizar y revisar los documentos de ingreso y egreso de bienes",
    "Coordinar con los entes de control, la información de registro de bienes y procedimientos utilizados",
    "Mantener actualizado el inventario de los activos fijos y bienes no depreciables sujetos a control administrativo, su custodia y conservación, con el propósito de mantener actualizada la información del área",
    "Registrar en el sistema automatizado el ingreso de activos fijos adquiridos por la Compañía",
    "Controlar las solicitudes de transferencias de bienes de la Compañía, de acuerdo con petición de las diferentes áreas",
    "Custodiar los archivos institucionales referentes a los procesos relacionados con su gestión; así como mantener ordenado y con los documentos de respaldo",
    "Ejecutar los procesos de compras públicas inherentes a su unidad de gestión, esto incluirá la administración de contratos en caso de ser así asignado",
    "Proporcionar a las diferentes áreas de la Compañía, listados e informes que le soliciten en materia de activos fijos y bienes de control",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía"
  ] },
  { departamento: "JEFATURA ADMINISTRATIVA", cargo: "BODEGUERO/A", funciones: [
    "Realizar el control de las existencias mínimas en base a datos de consumos: mensuales, trimestrales y anuales con el propósito de evitar desabastecimiento del stock",
    "Ingresar y egresar diariamente los movimientos de los bienes y materiales de la bodega para actualización del Kardex y registro contable",
    "Coordinar con los diferentes departamentos las adquisiciones para un adecuado provisionamiento de: materiales, herramientas, equipos, suministros, repuestos entre otros, previo a un análisis de necesidades e históricos de consumos de años anteriores",
    "Recibir en bodega: bienes, materiales, herramientas, repuestos, equipos, suministros entre otros, verificando la orden de compra, guía de remisión y la respectiva factura",
    "Elaborar y legalizar las actas de entrega recepción de bodega de: bienes, materiales, herramientas, repuestos, suministros, equipos, entre otros",
    "Codificar, almacenar y custodiar los bienes existentes en bodega, según las normas establecidas, con el propósito de facilitar su ubicación evitando pérdidas y deterioro",
    "Revisar las órdenes de requerimientos internos, comparar con el stock de existencias en bodega y proceder con su entrega",
    "Realizar el levantamiento de inventarios físicos, rotativos de bienes y materiales existentes en la bodega",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser asi designado",
    "Custodiar los archivos institucionales referentes a los procesos relacionados con su gestión; así como mantener ordenado los documentos de respaldo",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo"
  ] },
  { departamento: "JEFATURA ADMINISTRATIVA", cargo: "AUXILIAR DE SERVICIOS GENERALES", funciones: [
    "Ejecutar trabajos de mantenimiento, reposición, reubicación o construcción menor de: instalaciones eléctricas, hidrosanitarias, telefónicas, tabiques, pintura, muebles y otros; así como el desalojo de materiales y deshechos",
    "Realizar la limpieza del mobiliario, equipos, instalaciones de la compañía de ser requerido por el jefe inmediato",
    "Recibir órdenes de trabajo y preparar las herramientas y materiales",
    "Realizar el mantenimiento de los jardines y áreas verdes",
    "Realizar el arreglo y adecuación de las instalaciones de la CEM Austrogas",
    "Realizar la siembra y mantenimiento de plantas en las instalaciones de la CEM Austrogas",
    "Realizar la recolección de basura de las instalaciones",
    "Realizar la limpieza de los parqueaderos",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir con las normas de seguridad y salud en el trabajo"
  ] },
  { departamento: "JEFATURA ADMINISTRATIVA", cargo: "CONSERJE", funciones: [
    "Realizar la limpieza de los utensilios de cafetería, mobiliario, equipos e instalaciones",
    "Atender los servicios de cafetería",
    "Brindar apoyo en actividades administrativas y de logística solicitadas por el jefe inmediato",
    "Mantener dotado los baños con suministros de aseo personal",
    "Realizar la recolección de basura de las oficinas",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir las normas de seguridad y salud en el trabajo"
  ] },
  { departamento: "JEFATURA ADMINISTRATIVA", cargo: "CHOFER VEHÍCULO PESADO", funciones: [
    "Transportar personal, bienes, materiales, documentos, equipos, cilindros de gas licuado de petróleo, graneleros, de acuerdo a las necesidades de la compañía",
    "Conducir los vehículos asignados por la Compañía",
    "Registrar y reportar en el documento correspondiente: destinos, tiempos, kilometraje, consumo de combustible, daños mecánicos y daños materiales",
    "Realizar la revisión del vehículo asignado, para constatar su eficiente estado: lavado, estado de motor, estado de llantas, sistema mecánico, sistema hidráulico, sistema eléctrico",
    "Realizar reparaciones sencillas y limpieza del vehículo",
    "Realizar otras actividades encomendadas por el jefe inmediato relacionadas con la gestión del área",
    "Reportar al jefe inmediato las novedades relacionadas con incidentes o accidentes de trabajo",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía",
    "Cumplir con las normas de seguridad y salud en el trabajo",
    "Cumplir con las políticas y procedimientos definidos por la Compañía"
  ] },
  { departamento: "JEFATURA ADMINISTRATIVA", cargo: "CHOFER ADMINISTRATIVO", funciones: [
    "Transportar personal, bienes, materiales, documentos, equipos, dentro o fuera del área de influencia de la Compañía",
    "Conducir los vehículos asignados por la Compañía para el desarrollo de sus funciones",
    "Registrar y reportar en el documento correspondiente: kilometraje, consumo de combustible, daños mecánicos y daños materiales",
    "Realizar la revisión del vehículo asignado, para constatar su eficiente estado: lavado, revisado motor, estado de llantas, sistema mecánico, sistema hidráulico, sistema eléctrico",
    "Realizar reparaciones sencillas y limpieza del vehículo",
    "Cumplir con las normas de seguridad y salud en el trabajo",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía",
    "Colaborar con la comunidad cuando se presenten estados de emergencia",
    "Reportar al jefe inmediato las novedades relacionadas con incidentes o accidentes de trabajo",
    "Cumplir con las disposiciones solicitadas por su jefe inmediato"
  ] },
  { departamento: "JEFATURA ADMINISTRATIVA", cargo: "AUXILIAR DE BODEGA", funciones: [
    "Ingresar y egresar diariamente los movimientos de los bienes y materiales de la bodega para actualización del kardex y registro contable",
    "Recibir en bodega: bienes, materiales, herramientas, repuestos, equipos, suministros entre otros, verificando la orden de compra y la respectiva factura",
    "Elaborar y legalizar las actas de entrega recepción de: bienes, materiales, herramientas, repuestos, suministros, equipos, entre otros",
    "Mantener organizada la bodega por ítems y productos",
    "Codificar, almacenar y custodiar los bienes existentes en bodega, según las normas establecidas, con el propósito de facilitar su ubicación evitando pérdidas y deterioro",
    "Custodiar los archivos institucionales referentes a los procesos relacionados con su gestión; así como mantener ordenado y con los documentos de respaldo",
    "Entregar y recibir: bienes, materiales, equipos y herramientas, suministros, entre otros, de acuerdo a las autorizaciones y procesos establecidos por la compañía, todo esto mediante su entrega",
    "Participar en el levantamiento de inventarios físicos de bienes y materiales existentes en la Bodega",
    "Mantener el orden y limpieza de la Bodega",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía",
    "Cumplir las normas de seguridad y salud en el trabajo",
    "Cumplir con las políticas y procedimientos definidos por la Compañía"
  ] },
  { departamento: "ENVASADO, MANTENIMIENTO Y ALMACENAMIENTO", cargo: "JEFE/A DE ENVASADO MANTENIMIENTO Y ALMACENAMIENTO", funciones: [
    "Planificar, supervisar y controlar todos los procesos de las áreas de envasado, almacenamiento, mantenimiento de cilindros y mantenimiento general",
    "Evaluar y vigilar el cumplimiento de la planificación de mantenimiento de las instalaciones, maquinaria y equipos de Envasado, Mantenimiento y Almacenamiento",
    "Coordinar y gestionar los requerimientos operativos con EP Petroecuador en caso de abastecimiento de GLP",
    "Gestionar la aplicación de normas para garantizar la calidad de los servicios que brinda la Compañía",
    "Planificar el diseño, la ejecución de obras en la planta, que permitan la expansión y mejoramiento de los servicios de envasado, almacenamiento y mantenimiento",
    "Elaborar y poner a consideración de la Gerencia: manuales, políticas y procedimientos para la efectiva gestión de la Jefatura de Envasado, Mantenimiento y Almacenamiento",
    "Analizar y evaluar la información estadística generada con el propósito de sugerir mejoras que permitan entregar un mejor servicio",
    "Planificar con el personal la gestión inherente a los procesos de producción y mantenimiento, en aplicación de las normas que permitan garantizar la calidad del servicio y el cumplimiento de los objetivos institucionales",
    "Asesorar y brindar información especializada a los organismos externos y la Gerencia",
    "Elaborar informes periódicos de la gestión cumplida",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser asi designado",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir con las normas de seguridad y salud en el trabajo",
    "Velar por el buen uso de los recursos, equipos e instalaciones, asignados por la Compañía"
  ] },
  { departamento: "ENVASADO, MANTENIMIENTO Y ALMACENAMIENTO", cargo: "TÉCNICO/A DE PRODUCCIÓN", funciones: [
    "Realizar el análisis de los procesos productivos de planta y proponer mejoras para su funcionamiento",
    "Elaborar procedimientos y procesos para mejorar la producción de planta de la Compañía",
    "Realizar el estudio de tiempos y movimientos del proceso productivo, considerando la maquinaria, equipos y personal disponible",
    "Validar las órdenes de producción, de acuerdo con requerimientos de la Jefatura Comercial, con el propósito de proceder con la producción diaria",
    "Revisar los reportes de envasado, almacenamiento y mantenimiento de cilindros, con el propósito de proponer mejoras al proceso",
    "Verificar que se cumplan los procedimientos definidos en las Unidades de la Jefatura de Envasado, Mantenimiento y Almacenamiento",
    "Coordinar y controlar el cumplimiento de los mantenimientos programados en la planta",
    "Planificar y ejecutar pruebas de campo en la planta, a fin de determinar mejoras en los procesos productivos",
    "Revisar los informes técnicos de supervisores para la adquisición de bienes, obras y/o servicios relacionados con su gestión",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser asi designado",
    "Proponer y aplicar indicadores de gestión, para medir el cumplimiento de los objetivos definidos en la Jefatura de Envasado, Mantenimiento y Almacenamiento",
    "Mantener actualizado, ordenado y archivado los documentos de la Jefatura de Envasado, Mantenimiento y Almacenamiento",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía",
    "Cumplir y hacer cumplir las políticas y procedimientos definidos por la Compañía",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo"
  ] },
  { departamento: "ENVASADO, MANTENIMIENTO Y ALMACENAMIENTO", cargo: "SUPERVISOR/ A DE ALMACENAMIENTO-CUENCA/VENTANAS", funciones: [
    "Realizar la planificación de la logística de transporte de GLP en autotanques desde los terminales de EP Petroecuador hacia las plantas Cuenca y Ventanas de la CEM AUSTROGAS",
    "Realizar el seguimiento de cada uno de los autotanques en las rutas programadas a través del uso de medios electrónicos",
    "Autorizar el ingreso de los autotanques a la planta en el orden programado",
    "Realizar el pesaje de cada autotanque previo al inicio del proceso de descarga de GLP",
    "Realizar la descarga de gas licuado de petróleo de los autotanques hacia los tanques estacionarios de almacenamiento",
    "Llevar el control diario del movimiento de GLP, tanto de ingresos como de egresos",
    "Realizar el despacho de gas licuado de petróleo, en los camiones graneleros, para ser distribuido en las instalaciones centralizadas de clientes",
    "Elaborar la orden de producción del despacho de GLP realizado en los camiones cisterna",
    "Coordinar la entrega de GLP, para el abastecimiento de los pedidos de clientes industriales",
    "Llevar el control diario de GLP despachado en los camiones graneleros",
    "Elaborar las órdenes de producción para el envasado diario en la unidad de Envasado y Despacho",
    "Realizar el control de ingresos y excedentes diarios de GLP entregado a la unidad de Envasado y Despacho",
    "Realizar el control diario del cupo de GLP doméstico asignado por la Agencia de Regulación y Control Hidrocarburífero",
    "Coordinar el mantenimiento de los equipos e instalaciones asignados a la Unidad de Almacenamiento",
    "Elaborar informes con detalle de viajes realizados por cada tanquero, para proceder con el pago",
    "Proponer indicadores para dar seguimiento a la gestión del área",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser asi designado",
    "Velar por el buen uso de los recursos y equipos asignados por la compañía",
    "Manejar los archivos de documentos relacionados con su gestión",
    "Cumplir y hacer cumplir las políticas y procedimientos definidos por la compañía",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo",
    "Cumplir con las actividades designadas por su Jefe inmediato inherentes a su puesto de trabajo"
  ] },
  { departamento: "ENVASADO, MANTENIMIENTO Y ALMACENAMIENTO", cargo: "SUPERVISOR/A DE ENVASADO Y DESPACHO", funciones: [
    "Realizar el cuadre de despachos diarios con los reportes remitidos por la Jefatura Comercial",
    "Realizar el inventario permanente de los cilindros de GLP que se encuentran en la Unidad de Envasado y Despacho; y, registrar su movimiento en el sistema automatizado de la Compañía",
    "Planificar y asignar responsabilidades al personal a cargo para el desarrollo del proceso de envasado",
    "Verificar el número de cilindros de GLP que ingresan y salen en los vehículos de los clientes para su abastecimiento",
    "Supervisar la correcta clasificación de los cilindros de GLP, a fin de determinar su estado",
    "Custodiar los cilindros que se encuentran en la bodega a su cargo",
    "Verificar que los kilogramos despachados por almacenamiento sean iguales a la facturación realizada y al envasado de pedidos realizados por los distribuidores, determinando saldos",
    "Coordinar el mantenimiento de los equipos e instalaciones asignados a la Unidad de Envasado y Despacho",
    "Registrar los datos relacionados al proceso de envasado de cilindros de GLP",
    "Supervisar el traslado de los cilindros de GLP, para su mantenimiento",
    "Elaborar y presentar a su jefe inmediato y a los organismos de control, los informes sobre labores cumplidas",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía",
    "Elaborar las actas entrega recepción de los cilindros de GLP que no se encuentran operativos, para ser entregados al área de mantenimiento de cilindros",
    "Realizar la entrega de cilindros de GLP a los distribuidores, en base a préstamos transitorios o permanentes, verificando los documentos de soporte remitidos por la Jefatura Comercial",
    "Recibir la devolución de préstamos transitorios y permanentes de los distribuidores de cilindros de GLP, verificando la información remitida por la Jefatura Comercial",
    "Proponer indicadores para dar seguimiento a la gestión del área",
    "Coordinar con su jefe inmediato el intercambio de cilindros de otras comercializadoras",
    "Recibir y comprobar los cilindros de GLP con carga que fueron despachados a los distribuidores y que se encuentran defectuosos; emite el respectivo comprobante de devolución para el trámite en la Jefatura Comercial",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser asi designado",
    "Coordinar y controlar el cumplimiento de los mantenimientos programados en la planta",
    "Cumplir y hacer cumplir las políticas y procedimientos definidos por la Compañía",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo",
    "Cumplir con las actividades designadas por su Jefe inmediato inherentes a su puesto de trabajo"
  ] },
  { departamento: "ENVASADO, MANTENIMIENTO Y ALMACENAMIENTO", cargo: "SUPERVISOR/A DE MATENIMIENTO DE CILINDROS", funciones: [
    "Supervisar que se realicen las pruebas de calidad durante todas las fases del proceso de mantenimiento de cilindros",
    "Supervisar, asignar y coordinar las labores diarias del personal a su cargo",
    "Elaborar órdenes de producción para el mantenimiento de cilindros de GLP",
    "Realizar el inventario permanente de los cilindros de GLP, que se encuentran para mantenimiento y registrar su movimiento en el sistema automatizado de la Compañía",
    "Custodiar los cilindros que se encuentran en la bodega a su cargo",
    "Realizar el control de insumos y materiales utilizados en el proceso de mantenimiento de cilindros de GLP",
    "Elaborar y presentar a su jefe inmediato y a los organismos de control, los informes sobre labores cumplidas",
    "Coordinar el mantenimiento de los equipos e instalaciones de la Unidad de Mantenimiento de Cilindros",
    "Planificar junto al jefe inmediato el mantenimiento de los cilindros de GLP de acuerdo a la producción",
    "Registrar, los datos de control de mantenimiento de cilindros de GLP y las pruebas de calidad",
    "Proponer indicadores para dar seguimiento a la gestión del área",
    "Elaborar las actas entrega recepción de los cilindros de GLP que no se encuentran operativos, para su mantenimiento",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser asi designado",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía",
    "Cumplir y hacer cumplir las políticas y procedimientos definidos por la Compañía",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo",
    "Cumplir con las actividades encomendadas por su jefe inmediato inherentes a su puesto de trabajo"
  ] },
  { departamento: "ENVASADO, MANTENIMIENTO Y ALMACENAMIENTO", cargo: "TÉCNICO DE MANTENIMIENTO GENERAL", funciones: [
    "Planificar y coordinar las actividades, para la ejecución de mantenimientos preventivos y correctivos de los equipos, maquinaria e instalaciones eléctricas y mecánicas",
    "Coordinar el mantenimiento a los sistemas del tanque contenedor de los vehículos de reparto de gas licuado de petróleo",
    "Ejecutar las actividades para los mantenimientos preventivos y correctivos de los equipos, maquinaria e instalaciones de la Compañía",
    "Planificar, coordinar, supervisar y evaluar la ejecución de mantenimientos preventivos y correctivos programados con proveedores externos",
    "Coordinar con su jefe inmediato, lo relacionado con el personal, recursos económicos y materiales para la ejecución de los mantenimientos preventivos y correctivos",
    "Montaje de equipos fabricados y apoyo técnico en montaje de equipos adquiridos",
    "Elaborar el plan de trabajo y el presupuesto del área",
    "Elaborar y poner a consideración de su jefe inmediato: instructivos, manuales, procesos, respecto a equipos de las instalaciones de la Compañía",
    "Proponer indicadores para dar seguimiento a la gestión del área",
    "Elaborar informes relacionados con la gestión cumplida",
    "Elaborar informes técnicos para la adquisición de bienes, obras y/o servicios relacionados con su gestión",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual contractual esto incluirá la administración de contratos en caso de ser asi designado",
    "Realizar propuestas de innovación a través de proyectos de implantación de mejoras, para las instalaciones o equipos de la Compañía",
    "Realizar planos y detalles técnicos de equipos, maquinaria e infraestructura solicitados por su jefe inmediato",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía",
    "Cumplir y hacer cumplir las políticas, reglamentos y procedimientos definidos por la Compañía",
    "Cumplir y hacer cumplir las normas de seguridad, ambiente y salud en el trabajo",
    "Custodiar los archivos de documentos relacionados con su gestión"
  ] },
  { departamento: "ENVASADO, MANTENIMIENTO Y ALMACENAMIENTO", cargo: "OPERADOR DE ALMACENAMIENTO", funciones: [
    "Realizar el seguimiento de cada uno de los autotanques en las rutas programadas a través de medios electrónicos",
    "Autorizar el ingreso de los autotanques a la planta en el orden programado",
    "Realizar el pesaje de cada autotanque previo al inicio del proceso de descarga de GLP",
    "Realizar la descarga de gas licuado de petróleo de los autotanques hacia los tanques estacionarios de almacenamiento",
    "Llevar el control diario del movimiento de GLP, tanto de ingresos como de egresos",
    "Realizar el despacho de gas licuado de petróleo, en los camiones graneleros, para ser distribuido en las instalaciones centralizadas de clientes",
    "Elaborar la orden de producción del despacho de GLP realizado en los camiones cisterna",
    "Llevar el control diario de GLP despachado en los camiones graneleros",
    "Elaborar las órdenes de producción para el envasado diario en la Unidad de Envasado y Despacho",
    "Coordinar el mantenimiento de los equipos e instalaciones asignados a la Unidad de Almacenamiento",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía",
    "Cumplir y hacer cumplir las políticas y procedimientos definidos por la Compañía",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo",
    "Cumplir con las actividades designadas por su Jefe inmediato inherentes a su puesto de trabajo"
  ] },
  { departamento: "ENVASADO, MANTENIMIENTO Y ALMACENAMIENTO", cargo: "TÉCNICO ENVASADO Y DESPACHO", funciones: [
    "Apoyar en la toma del inventario inicial diario de los cilindros que se encuentran operativos para su envasado, existentes en las instalaciones de la Unidad de Envasado y Despacho, siendo responsable conjuntamente con el Supervisor de Envasado y Despacho cuando existen pérdida de cilindros",
    "Colaborar en la supervisión de la asignación de responsabilidades al personal del área de Envasado y Despacho",
    "Asistir en la revisión de las órdenes de producción, con relación a los pedidos de las comercializadoras",
    "Ayudar con el registro de número de cilindros de GLP que ingresan y egresan de la Unidad de Envasado y Despacho, en los vehículos de las comercializadoras",
    "Revisar que las órdenes de producción estén de acuerdo con los requerimientos del área Comercial, para realizar la producción diaria",
    "Asistir en la clasificación de los cilindros de GLP, para determinar su estado",
    "Colaborar en la ejecución del procedimiento los préstamos y devoluciones transitorias y/o permanente de cilindros a la red de distribución",
    "Realizar el encendido de las máquinas para iniciar con el proceso de producción",
    "Realizar el evacuado de los cilindros de GLP que requieren mantenimiento y enviar a la bodega de la Unidad de Mantenimiento de Cilindros",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo"
  ] },
  { departamento: "ENVASADO, MANTENIMIENTO Y ALMACENAMIENTO", cargo: "ESTIBADOR", funciones: [
    "Trasladar los cilindros de GLP, vacíos desde los camiones hacia el sistema transportador para el proceso de envasado de GLP, para ser llenados; y los cilindros llenos de GLP desde el sistema transportador hacia los camiones que realizarán la distribución",
    "Estibar cilindros llenos y vacíos dentro de las instalaciones de la CEM Austrogas",
    "Efectuar el estibaje de cilindros para el proceso de intercambio con otras comercializadoras, así como los cilindros no operativos para ser enviados al proceso de mantenimiento",
    "Realizar las actividades encomendadas por el jefe inmediato",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía",
    "Cumplir las políticas, reglamentos, normas de seguridad; y, demás procedimientos definidos por la Compañía"
  ] },
  { departamento: "ENVASADO, MANTENIMIENTO Y ALMACENAMIENTO", cargo: "OPERADOR DE MANTENIMIENTO DE CILINDROS", funciones: [
    "Realizar las labores previas al proceso de mantenimiento de cilindros: clasificación, extracción de válvulas, inertizado",
    "Trasladar los cilindros hacia la Unidad de Mantenimiento de Cilindros",
    "Realizar el mantenimiento del cilindros, cumpliendo el procedimiento establecido",
    "Realizar las pruebas de cumplimiento de normas de calidad establecidas para el taller tipo B",
    "Extraer la válvula del cilindro para procederlo a inertizar",
    "Elaborar el proceso de granallado del cilindro para posteriormente pintarlo",
    "Realizar pruebas de válvulas antes de su reutilización, de ser el caso",
    "Elaborar el terminado del cilindro: colocar y asegurar la válvula, y el logotipo serigrafiado de la Compañía",
    "Transportar y clasificar los cilindros, a fin de determinar su enderezado o corte",
    "Recibir órdenes de trabajo, preparar las herramientas y materiales",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía",
    "Cumplir con las políticas y procedimientos definidos por la Compañía",
    "Cumplir las normas de seguridad y salud en el trabajo",
    "Realizar actividades solicitadas por el jefe inmediato y apoyar a las áreas que lo requieran, incluyendo actividades administrativas básicas"
  ] },
  { departamento: "JEFATURA FINANCIERA", cargo: "JEFE/A FINANCIERO/A", funciones: [
    "Analizar periódicamente la situación financiera de la Compañía y recomendar los ajustes presupuestarios requeridos según los resultados.",
    "Revisar y analizar la información y documentación pertinente previo a la entrega a los entes de control (Contraloría General del Estado, SRI, Superintendencia de Compañías, ARCERNNR, Municipios, Ministerio de Finanzas, Auditoría Externa, entre otros).",
    "Aplicar las medidas correctivas recomendadas por los organismos reguladores o de auditoría interna y externa.",
    "Cumplir con las leyes, normas y regulaciones impartidas por los organismos de control financiero.",
    "Revisar, aprobar y autorizar las transferencias bancarias para los pagos solicitados por los diferentes departamentos de AustroGAS C.E.M.",
    "Elaborar y dirigir el ciclo presupuestario en sus fases de programación, formulación, aprobación, ejecución, seguimiento, evaluación y liquidación.",
    "Elaborar y proponer a Gerencia los manuales, políticas y procedimientos en materia financiera y contable.",
    "Recopilar y analizar la información departamental para elaborar los informes que deben presentarse ante Gerencia, Directorio y Junta General de Accionistas.",
    "Elaborar los flujos de caja proyectados, controlar la ejecución presupuestaria de egresos e inversiones, y emitir certificaciones presupuestarias.",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual, incluyendo la administración de contratos asignados.",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía.",
    "Velar por el buen uso de los recursos, equipos e instalaciones asignados."
  ] },
  { departamento: "JEFATURA FINANCIERA", cargo: "ASISTENTE DE CONTROL INTERNO Y RECEPCIÓN", funciones: [
    "Administrar y mantener ordenados los archivos correspondientes a su gestión con las seguridades requeridas.",
    "Elaborar informes de control, entrega y recepción de documentos.",
    "Orientar a clientes en recepción, direccionamiento y atención telefónica de comunicados de la empresa.",
    "Realizar actividades de control en las diferentes áreas de la empresa en coordinación con la Jefatura Financiera.",
    "Realizar el control de documentación previo a devengar recursos económicos de la empresa.",
    "Brindar apoyo general a las diferentes áreas del Departamento Financiero.",
    "Llevar a cabo los procesos de contratación pública y administración de contratos en caso de ser asignado.",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía.",
    "Velar por el buen uso de los recursos, equipos e instalaciones asignados."
  ] },
  { departamento: "JEFATURA FINANCIERA", cargo: "CONTADOR/A GENERAL", funciones: [
    "Revisar y analizar información financiera conforme a NIIF, normativa tributaria, societaria, presupuestaria y laboral.",
    "Elaborar y enviar declaraciones tributarias en línea ante el SRI (IVA, Retenciones en la fuente, Impuesto a la Renta anual y anexos).",
    "Preparar y enviar estados financieros para el control anual de la Superintendencia de Compañías.",
    "Preparar y realizar pagos de tasas, impuestos y contribuciones a instituciones públicas.",
    "Elaborar el cuadro de integración de capital y distribución de dividendos para la Junta General de Accionistas.",
    "Realizar control interno transaccional, conciliación del ingreso/costo de ventas y conciliación mensual del inventario de GLP.",
    "Revisar y legalizar registros contables, realizar cierres mensuales, registrar transferencias a Banco Central del Ecuador (BCE) y conciliar Propiedad, Planta y Equipo (PPE).",
    "Atender requerimientos de auditoría financiera y exámenes especiales.",
    "Llevar a cabo los procesos de contratación pública y administración de contratos.",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía.",
    "Velar por el buen uso de los recursos, equipos e instalaciones asignados."
  ] },
  { departamento: "JEFATURA FINANCIERA", cargo: "ANALISTA FINANCIERO", funciones: [
    "Efectuar control previo a transferencias de pago examinando la documentación de soporte (suficiencia, pertinencia y confiabilidad).",
    "Contabilizar compras de proveedores, efectuar retenciones en la fuente e ingresar beneficiarios al sistema bancario.",
    "Elaborar el consolidado diario de pagos y conciliar compras e impuestos para declaraciones de anexos.",
    "Realizar enlace, compensación e informes de cartera por cobrar/pagar con Petroecuador.",
    "Realizar la conciliación bancaria del Banco Central del Ecuador (BCE) para revisión del Contador General.",
    "Controlar, seguir y custodiar las garantías contractuales entregadas a la compañía.",
    "Manejar y custodiar el libro de acciones y accionistas de la Compañía.",
    "Revisar costos de GLP en el sistema automatizado y elaborar flujos de caja proyectados.",
    "Llevar a cabo los procesos de contratación pública y administración de contratos.",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía.",
    "Velar por el buen uso de los recursos, equipos e instalaciones asignados."
  ] },
  { departamento: "JEFATURA FINANCIERA", cargo: "ANALISTA DE GESTIÓN DE CARTERA", funciones: [
    "Analizar el riesgo económico para la evaluación y aprobación de solicitudes de crédito de clientes.",
    "Proponer políticas y procedimientos de evaluación de riesgo crediticio y coordinar convenios de pago/cobro con el departamento Jurídico.",
    "Supervisar la recaudación por ventas de GLP, verificar cierres de caja diarios y atender reclamos de facturación.",
    "Reportar el detalle de cartera a la Superintendencia de Bancos mediante el Sistema de Registro de Datos Crediticios.",
    "Registrar pagos y cancelaciones de clientes en el sistema, gestionar comprobantes de retención, notas de crédito y débito.",
    "Realizar conciliaciones bancarias de cuentas de recaudación y caja matriz.",
    "Custodiar y controlar la vigencia de garantías entregadas por los clientes.",
    "Llevar a cabo los procesos de contratación pública y administración de contratos.",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía.",
    "Velar por el buen uso de los recursos, equipos e instalaciones asignados."
  ] },
  { departamento: "JEFATURA FINANCIERA", cargo: "ANALISTA DE CONTROL PRESUPUESTARIO", funciones: [
    "Dar seguimiento integral a las etapas del ciclo presupuestario: Programación, Formulación, Aprobación, Ejecución, Seguimiento, Clausura y Liquidación.",
    "Elaborar y consolidar la proforma presupuestaria anual junto con las Jefaturas Departamentales.",
    "Efectuar conciliaciones entre lo presupuestado y lo ejecutado para evaluar avances y desviaciones.",
    "Emitir y registrar certificaciones presupuestarias, controlando saldos comprometidos y por comprometer.",
    "Efectuar el control previo y compromisos presupuestarios en el sistema informático previo al devengamiento.",
    "Analizar y tramitar reformas presupuestarias según requerimientos institucionales.",
    "Realizar la liquidación presupuestaria al cierre del ejercicio económico.",
    "Llevar a cabo los procesos de contratación pública y administración de contratos.",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía.",
    "Velar por el buen uso de los recursos, equipos e instalaciones asignados."
  ] },
  { departamento: "PLANIFICACIÓN, SEGURIDAD Y AMBIENTE", cargo: "JEFE/A DE PLANIFICACIÓN, SEGURIDAD Y AMBIENTE", funciones: [
    "Planificar con las diferentes áreas y departamentos los planes de negocio, proyectos o programas a consideración de Gerencia.",
    "Realizar estudios de rentabilidad económica y financiera para proyectos requeridos por la empresa.",
    "Coordinar y elaborar el plan estratégico de la Compañía.",
    "Proporcionar información de su área para la elaboración del informe anual de gestión.",
    "Cumplir con las leyes, normas y regulaciones impartidas por los organismos de control.",
    "Asesorar a la Gerencia y demás áreas en lo relacionado con el funcionamiento del sistema integrado de seguridad y ambiente.",
    "Aplicar las medidas correctivas recomendadas por entes reguladores u organismos de auditoría.",
    "Analizar y evaluar el cumplimiento de indicadores de gestión definidos por las diferentes áreas.",
    "Reportar la gestión cumplida y preparar la documentación requerida por Gerencia.",
    "Realizar estudios de costos por servicios que brinda la Compañía.",
    "Administrar y proponer mejoras continuas al sistema integrado de gestión de seguridad y ambiente.",
    "Gestionar la mejora continua de procesos institucionales y elaborar manuales, políticas y procedimientos.",
    "Elaborar informes técnicos para la adquisición de bienes, obras y/o servicios del área.",
    "Llevar a cabo los procesos de contratación pública (fases preparatoria, precontractual y contractual y administración de contratos).",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo y ambiente.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía.",
    "Velar por el buen uso de los recursos, equipos e instalaciones asignados."
  ] },
  { departamento: "PLANIFICACIÓN, SEGURIDAD Y AMBIENTE", cargo: "TÉCNICO/A DE SEGURIDAD E HIGIENE INDUSTRIAL", funciones: [
    "Elaborar reglamentos, manuales y procedimientos de seguridad industrial e higiene laboral en concordancia con leyes vigentes.",
    "Coordinar y gestionar los requerimientos de equipos de protección personal (EPP) e implementos de seguridad.",
    "Investigar y realizar el seguimiento integral de accidentes e incidentes de trabajo.",
    "Realizar inspecciones periódicas de seguridad industrial y proponer solutions correctivas/preventivas.",
    "Verificar, registrar y controlar equipos y herramientas para prevención de incendios y mitigación de riesgos laborales.",
    "Ejecutar el cronograma de trabajo asignado al área de seguridad industrial.",
    "Coordinar la gestión de seguridad industrial con las distintas áreas institucionales y entes externos.",
    "Definir y evaluar los indicadores de gestión del área de seguridad e higiene industrial.",
    "Llevar el control de extintores, sistemas contra incendios y fichas técnicas de recarga y mantenimiento.",
    "Capacitar al personal en seguridad industrial, prevención de incendios y conformación de brigadas de emergencia.",
    "Gestionar la implementación y mantenimiento de la señalética de seguridad según normas internacionales.",
    "Llevar a cabo procesos de contratación pública y administración de contratos asignados.",
    "Cumplir y hacer cumplir las normas de seguridad y salud en el trabajo.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía.",
    "Velar por el buen uso de los recursos, equipos e instalaciones asignados.",
    "Elaborar informes para adquisición de bienes y servicios de su área.",
    "Cumplir actividades encomendadas por su Jefe inmediato."
  ] },
  { departamento: "PLANIFICACIÓN, SEGURIDAD Y AMBIENTE", cargo: "TÉCNICO/A AMBIENTAL", funciones: [
    "Desarrollar proyectos de investigación e innovación enfocados en tecnologías limpias y uso eficiente de la energía.",
    "Elaborar, evaluar y dar seguimiento a estudios de impacto ambiental e informes de cumplimiento para órganos de control.",
    "Ejecutar las actividades del Plan de Manejo Ambiental y coordinar las auditorías ambientales internas y externas.",
    "Investigar riesgos ambientales y supervisar el cumplimiento de normativas de seguridad y protección ambiental.",
    "Capacitar al personal de la empresa en gestión ambiental, manejo de residuos y sustentabilidad.",
    "Llevar a cabo procesos de contratación pública y administración de contratos en materias ambientales.",
    "Cumplir y hacer cumplir las normas de seguridad, salud y medio ambiente.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía.",
    "Velar por el buen uso de los recursos, equipos e instalaciones asignados.",
    "Realizar actividades encomendadas por la Jefatura inmediata."
  ] },
  { departamento: "JEFATURA DE TECNOLOGÍAS DE LA INFORMACIÓN", cargo: "JEFE/A DE TECNOLOGÍAS DE LA INFORMACIÓN", funciones: [
    "Reportar la gestión cumplida del departamento, así como preparar documentación requerida por la Gerencia.",
    "Aplicar medidas correctivas recomendadas por entes reguladores o de auditoría interna o externa.",
    "Administrar el Presupuesto asignado a la jefatura para contratar la tecnología más adecuada para la empresa.",
    "Identificar las necesidades y generar planes para las áreas de la compañía en las que las nuevas tecnologías puedan resultar una mejora del funcionamiento de la compañía.",
    "Supervisar el desarrollo normal de las actividades de toda la unidad para que estas se realicen dentro de los plazos establecidos.",
    "Planificar con las diferentes áreas y departamentos de la Compañía proyectos o programas que serán puestos a consideración de la gerencia para su aprobación y ejecución.",
    "Solucionar los problemas con los sistemas informáticos de la compañía o a su vez delegar a quien corresponda de acuerdo al requerimiento.",
    "Comprobar que los sistemas de copias de seguridad de los usuarios y equipos informáticos se encuentren funcionando de manera adecuada.",
    "Gestionar la seguridad de los datos y bases de datos dentro de la empresa, esto con el objetivo de que la información esté al alcance de las personas adecuadas y autorizadas.",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser así asignado.",
    "Elaborar y poner a consideración de la Gerencia: manuales, políticas y procedimientos para la efectiva gestión del departamento y sus unidades a cargo.",
    "Cumplir con las normas de seguridad y salud en el trabajo.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía."
  ] },
  { departamento: "JEFATURA DE TECNOLOGÍAS DE LA INFORMACIÓN", cargo: "ANALISTA DE REDES Y SEGURIDAD INFORMÁTICA", funciones: [
    "Diseñar las redes de comunicaciones de la empresa.",
    "Administrar, optimizar y asegurar las redes de comunicaciones de la empresa.",
    "Diagnosticar problemas en la infraestructura de redes y servidores para generar soluciones a los mismos.",
    "Actualizar los servidores de datos y del equipo de red.",
    "Implementar y revisar los controles de seguridad para salvaguardar los archivos digitales y la infraestructura electrónica de la compañía.",
    "Ejecutar acciones frente a incidentes de violación de las medidas de seguridad electrónica y a los ataques de virus informáticos.",
    "Gestionar la protección de archivos digitales contra modificación para satisfacer las necesidades de procesamiento de datos de emergencia.",
    "Brindar asistencia tecnológica a los usuarios finales.",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser así designado.",
    "Cumplir con las normas de seguridad y salud en el trabajo.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía.",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía."
  ] },
  { departamento: "JEFATURA DE TECNOLOGÍAS DE LA INFORMACIÓN", cargo: "ANALISTA DE SOPORTE Y DESARROLLO", funciones: [
    "Proponer y diseñar un sistema informático que podrá adaptarse para mejorar el funcionamiento de la empresa.",
    "Analizar los problemas presentados en el software de la empresa y buscar una solución de manera interna o externa.",
    "Diseñar, gestionar y mantener las bases de datos optimizadas, reorganizándolas para hacerlas más eficientes.",
    "Administrar la base de datos para que sea segura y se utilice con eficacia cumpliendo con la normativa indicada.",
    "Coordinar la asistencia y soporte a proveedores externos y clientes internos en procesos referentes a sus aplicativos.",
    "Diseñar e implementar reportes con información requerida por entes reguladores o de auditoría y clientes internos.",
    "Capacitar y asistir al personal de la empresa en el uso adecuado de los sistemas informáticos.",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser así designado.",
    "Velar por el buen uso de los recursos y equipos informáticos.",
    "Cumplir con las normas de seguridad y salud en el trabajo.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía."
  ] },
  { departamento: "PROCESOS ADJETIVOS DE ASESORÍA", cargo: "ABOGADO/A", funciones: [
    "Comparecer en los juicios que se encuentren en proceso y que corresponden a la Compañía, asumiendo su defensa en caso de ser solicitado por la máxima autoridad.",
    "Elaborar contratos para la prestación de bienes y/o servicios y ejecución de obras.",
    "Servir de órgano de consulta y asesorar en los aspectos jurídicos, a todas las áreas de la Compañía.",
    "Realizar resoluciones de aprobación, adjudicación, declaración de desiertos, cancelación y demás acciones legales relacionadas con los procesos de contratación pública.",
    "Revisar y/o elaborar convenios, contratos, concesiones, autorizaciones o permisos que se celebren; y, en general todo acto o contrato a suscribirse con personas naturales o jurídicas que asumen compromisos y obligaciones con la Compañía.",
    "Elaborar los Informes de Viabilidad para la ejecución de los procesos de Contratación Pública.",
    "Elaborar los documentos y trámites Notariales que sean requeridos por la Compañía.",
    "Llevar un control del estado que en el que se encuentran los juicios en la página de la función judicial.",
    "Apoyar en la conformación de comisiones para la contratación de bienes, obras y/o servicios.",
    "Realizar trámites administrativos con organismos externos, de acuerdo con las necesidades institucionales.",
    "Despachar y entregar los contratos por diferente índole a las áreas de la Compañía.",
    "Realizar los trámites necesarios para la renovación actual de la Casilla Judicial.",
    "Elaborar los procesos de compras públicas inherentes a su unidad de gestión, desde sus fases preparatorias, precontractual y contractual, esto incluirá la Administración de contratos en caso de ser así asignado.",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía.",
    "Cumplir con las normas de seguridad y salud en el trabajo.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía."
  ] },
  { departamento: "PROCESOS ADJETIVOS DE ASESORÍA", cargo: "RELACIONADOR/A PÚBLICO/A", funciones: [
    "Elaborar y proponer el sistema de comunicación institucional.",
    "Planificar estrategias de contenidos y medios para satisfacer las necesidades informativas, de comunicación e imagen institucional.",
    "Elaborar y poner a consideración de la Gerencia, programas de responsabilidad social empresarial.",
    "Coordinar las relaciones con los medios locales y nacionales para promover la imagen institucional.",
    "Elaborar y poner a consideración de la Gerencia: manuales, políticas y procedimientos para la efectiva gestión del área.",
    "Asesorar en temas de comunicación, imagen institucional y responsabilidad social a las diferentes áreas y departamentos de la Compañía.",
    "Ejecutar y dar seguimiento el programa de responsabilidad social empresarial.",
    "Elaborar el plan de comunicación de la Compañía.",
    "Elaborar el sistema de comunicación externa a través de: boletines de prensa, ayudas memorias, entre otros.",
    "Coordinar conjuntamente con la Jefatura de Planificación Seguridad y Ambiente, la ejecución de los procesos de evaluación de la satisfacción de clientes sobre los servicios que entrega la Compañía.",
    "Realizar monitoreos de los medios externos a fin de conocer la percepción que tienen sobre los servicios que brinda la Compañía; así como realizar su seguimiento.",
    "Elaborar informes periódicos de gestión, así como preparar documentación requerida por la Gerencia.",
    "Realizar la logística y organización de los eventos de la Compañía.",
    "Dirigir campañas publicitarias de la Compañía, en coordinación con las diferentes áreas y departamentos.",
    "Elaborar y mantener actualizado el manual de imagen corporativa de la Compañía; así como velar por su aplicación.",
    "Manejar las redes sociales de la Compañía, mantener actualizada permanentemente la página WEB de la Compañía; y, gestionar los comentarios y opiniones de los usuarios.",
    "Elaborar Informes para la adquisición de bienes, obras y/o servicios relacionados con su gestión.",
    "Llevar a cabo los procesos de contratación pública, desde sus fases preparatoria, precontractual y contractual esto incluirá la administración de contratos en caso de ser así designado.",
    "Cumplir y hacer cumplir las normas de seguridad ambiental.",
    "Cumplir con las políticas y procedimientos definidos por la Compañía.",
    "Velar por el buen uso de los recursos y equipos asignados por la Compañía."
  ] }
];

const norm = (s: string) => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();

/** Busca el perfil de un cargo (tolerante a tildes, mayúsculas y variantes). */
export function perfilDeCargo(cargo: string): PerfilCargo | null {
  const c = norm(cargo || '');
  if (!c) return null;
  const exacto = PERFILES_CARGO.find((p) => norm(p.cargo) === c);
  if (exacto) return exacto;
  // Coincidencia parcial: el cargo registrado puede traer sufijos o variantes.
  return PERFILES_CARGO.find((p) => norm(p.cargo).includes(c) || c.includes(norm(p.cargo))) ?? null;
}

/** Funciones sugeridas de un cargo (las primeras n, por defecto las 6 principales). */
export function funcionesDeCargo(cargo: string, n = FUNCIONES_AUTOCOMPLETAR): string[] {
  return (perfilDeCargo(cargo)?.funciones ?? []).slice(0, n);
}

/** Lista de cargos para autocompletar en el formulario de trabajadores. */
export const CARGOS_CATALOGO: string[] = PERFILES_CARGO.map((p) => p.cargo).sort((a, b) => a.localeCompare(b, 'es'));
